version: "2"
services:
  world:
    build:
      context: https://github.com/dst-academy/docker-dontstarvetogether.git#v0.8.0:build
      args:
        MODS: 378160973,375859599,458940297
    container_name: world
    tty: true
    stdin_open: true
    command: dst-server start --update=all
    env_file: world.env
    ports:
      - "10999:10999/udp"
    volumes:
      - ./world:/var/lib/dsta/cluster
